/* eslint-disable */
/* Auto-generated by scripts/gen_types.py — do not edit by hand. */

export interface EffectBase {
  name: string;
  family: string;
  caliber_in?: number | null;
  colors?: string[];
  duration_s?: number | null;
  height_m?: number | null;
  burst_radius_m?: number | null;
  prefire_ms?: number | null;
  lift_time_ms?: number | null;
  sound_level?: string | null;
  recommended_use?: string | null;
  description?: string | null;
  vdl_params_json?: Record<string, unknown> | null;
}

export interface EffectCreate {
  name: string;
  family: string;
  caliber_in?: number | null;
  colors?: string[];
  duration_s?: number | null;
  height_m?: number | null;
  burst_radius_m?: number | null;
  prefire_ms?: number | null;
  lift_time_ms?: number | null;
  sound_level?: string | null;
  recommended_use?: string | null;
  description?: string | null;
  vdl_params_json?: Record<string, unknown> | null;
  source?: string;
  license?: string;
  provenance_url?: string | null;
  redistributable?: boolean;
}

export interface Effect {
  name: string;
  family: string;
  caliber_in?: number | null;
  colors?: string[];
  duration_s?: number | null;
  height_m?: number | null;
  burst_radius_m?: number | null;
  prefire_ms?: number | null;
  lift_time_ms?: number | null;
  sound_level?: string | null;
  recommended_use?: string | null;
  description?: string | null;
  vdl_params_json?: Record<string, unknown> | null;
  id: string;
  source: string;
  license: string;
  provenance_url: string | null;
  redistributable: boolean;
  imported_at: string;
  importer_version: string;
}

export interface Section {
  start_s: number;
  end_s: number;
  label: "intro" | "verse" | "chorus" | "bridge" | "drop" | "breakdown" | "outro" | "instrumental";
  energy: number;
  novelty: number;
}

export interface AudioAnalysis {
  duration_s: number;
  sample_rate: number;
  tempo_bpm: number;
  tempo_curve?: unknown[][];
  beats_s?: number[];
  downbeats_s?: number[];
  onsets_s?: number[];
  key?: string;
  mode?: "major" | "minor";
  loudness_curve?: number[];
  spectral_centroid_curve?: number[];
  stems?: Record<string, unknown>;
  sections?: Section[];
  mood_vector?: number[];
  mert_embedding?: number[];
  clap_embeddings?: unknown[][];
}

export interface Palette {
  primary?: string[];
  secondary?: string[];
  accent?: string[];
  rationale?: string;
}

export interface PlanSection {
  audio_section_index: number;
  intent: string;
  intensity: number;
  density_per_min: number;
  dominant_colors?: string[];
  preferred_effect_families?: string[];
  avoid?: string[];
}

export interface Motif {
  id: string;
  description: string;
  rule?: Record<string, unknown>;
}

export interface ShowPlan {
  title: string;
  concept: string;
  arc?: PlanSection[];
  palette: Palette;
  motifs?: Motif[];
  finale_concept: string;
  budget_distribution?: Record<string, unknown>;
}

export interface RankedEffect {
  effect_id: string;
  score: number;
  why: string;
  effect: Effect;
}

export interface EffectCandidates {
  per_section?: Record<string, unknown>;
  per_motif?: Record<string, unknown>;
}

export interface EffectsListResponse {
  items: Effect[];
  total: number;
}

export interface SemanticSearchRequest {
  query: string;
  limit?: number;
}

export interface SemanticSearchHit {
  effect: Effect;
  score: number;
  why: string;
}

export interface ProjectCreate {
  name: string;
}

export interface Project {
  name: string;
  id: string;
  created_at: string;
  updated_at: string;
  site_config_json: Record<string, unknown>;
  default_language: string;
}

export interface ProjectDetail {
  name: string;
  id: string;
  created_at: string;
  updated_at: string;
  site_config_json: Record<string, unknown>;
  default_language: string;
  shows?: ShowSummary[];
}

export interface ShowBase {
  song_path: string;
  song_sha256: string;
  constraints_json?: Record<string, unknown>;
  state?: string;
  state_json?: Record<string, unknown>;
}

export interface ShowCreate {
  song_path: string;
  song_sha256: string;
  constraints_json?: Record<string, unknown>;
  state?: string;
  state_json?: Record<string, unknown>;
  project_id: string;
}

export interface Show {
  song_path: string;
  song_sha256: string;
  constraints_json?: Record<string, unknown>;
  state?: string;
  state_json?: Record<string, unknown>;
  id: string;
  project_id: string;
  created_at: string;
  updated_at: string;
}

export interface ShowSummary {
  id: string;
  project_id: string;
  song_path: string;
  state: string;
  created_at: string;
  updated_at: string;
}
