/* eslint-disable */
/* Auto-generated by scripts/gen_types.py — do not edit by hand. */

export interface EffectBase {
  name: string;
  family: string;
  caliber_in?: number | null;
  colors?: string[];
  duration_s?: number | null;
  height_m?: number | null;
  burst_radius_m?: number | null;
  prefire_ms?: number | null;
  lift_time_ms?: number | null;
  sound_level?: string | null;
  recommended_use?: string | null;
  description?: string | null;
  vdl_params_json?: Record<string, unknown> | null;
}

export interface EffectCreate {
  name: string;
  family: string;
  caliber_in?: number | null;
  colors?: string[];
  duration_s?: number | null;
  height_m?: number | null;
  burst_radius_m?: number | null;
  prefire_ms?: number | null;
  lift_time_ms?: number | null;
  sound_level?: string | null;
  recommended_use?: string | null;
  description?: string | null;
  vdl_params_json?: Record<string, unknown> | null;
  source?: string;
  license?: string;
  provenance_url?: string | null;
  redistributable?: boolean;
}

export interface Effect {
  name: string;
  family: string;
  caliber_in?: number | null;
  colors?: string[];
  duration_s?: number | null;
  height_m?: number | null;
  burst_radius_m?: number | null;
  prefire_ms?: number | null;
  lift_time_ms?: number | null;
  sound_level?: string | null;
  recommended_use?: string | null;
  description?: string | null;
  vdl_params_json?: Record<string, unknown> | null;
  id: string;
  source: string;
  license: string;
  provenance_url: string | null;
  redistributable: boolean;
  imported_at: string;
  importer_version: string;
}

export interface EffectsListResponse {
  items: Effect[];
  total: number;
}

export interface SemanticSearchRequest {
  query: string;
  limit?: number;
}

export interface SemanticSearchHit {
  effect: Effect;
  score: number;
  why: string;
}

export interface ProjectCreate {
  name: string;
}

export interface Project {
  name: string;
  id: string;
  created_at: string;
  updated_at: string;
  site_config_json: Record<string, unknown>;
  default_language: string;
}

export interface ProjectDetail {
  name: string;
  id: string;
  created_at: string;
  updated_at: string;
  site_config_json: Record<string, unknown>;
  default_language: string;
  shows?: ShowSummary[];
}

export interface ShowBase {
  song_path: string;
  song_sha256: string;
  constraints_json?: Record<string, unknown>;
  state?: string;
  state_json?: Record<string, unknown>;
}

export interface ShowCreate {
  song_path: string;
  song_sha256: string;
  constraints_json?: Record<string, unknown>;
  state?: string;
  state_json?: Record<string, unknown>;
  project_id: string;
}

export interface Show {
  song_path: string;
  song_sha256: string;
  constraints_json?: Record<string, unknown>;
  state?: string;
  state_json?: Record<string, unknown>;
  id: string;
  project_id: string;
  created_at: string;
  updated_at: string;
}

export interface ShowSummary {
  id: string;
  project_id: string;
  song_path: string;
  state: string;
  created_at: string;
  updated_at: string;
}
