#!/usr/bin/env python3
"""Emit TypeScript interfaces from Pydantic JSON Schemas (see frontend/src/types/generated.ts)."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
BACKEND = ROOT / "backend"
OUT_PATH = ROOT / "frontend" / "src" / "types" / "generated.ts"

if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

from pyromind.models.effect import (  # noqa: E402
    Effect,
    EffectBase,
    EffectCreate,
    EffectsListResponse,
    SemanticSearchHit,
    SemanticSearchRequest,
)
from pyromind.models.audio import AudioAnalysis, Section  # noqa: E402
from pyromind.models.candidates import EffectCandidates, RankedEffect  # noqa: E402
from pyromind.models.plan import Motif, Palette, PlanSection, ShowPlan  # noqa: E402
from pyromind.models.project import Project, ProjectCreate, ProjectDetail  # noqa: E402
from pyromind.models.show import (  # noqa: E402
    Show,
    ShowBase,
    ShowCreate,
    ShowSummary,
)


def _ts_ident(name: str) -> str:
    """Return a safe TypeScript identifier."""
    return re.sub(r"[^a-zA-Z0-9_]", "_", name)


def _schema_to_ts(name: str, schema: dict[str, Any], defs: dict[str, Any]) -> str:
    """Render a JSON-schema subset as a TypeScript ``interface`` declaration."""
    lines: list[str] = [f"export interface {_ts_ident(name)} {{"]

    def resolve_ref(ref: str) -> dict[str, Any]:
        key = ref.split("/")[-1]
        return defs.get(key, {})

    def prop_type(prop_schema: dict[str, Any]) -> str:
        if "$ref" in prop_schema:
            ref_name = prop_schema["$ref"].split("/")[-1]
            return _ts_ident(ref_name)
        if "anyOf" in prop_schema:
            parts = [prop_type(p) for p in prop_schema["anyOf"] if p != {"type": "null"}]
            if {"type": "null"} in prop_schema["anyOf"]:
                return " | ".join(parts) + " | null" if parts else "null"
            return " | ".join(parts) if parts else "unknown"
        t = prop_schema.get("type")
        if t == "string":
            if "enum" in prop_schema:
                return " | ".join(json.dumps(e) for e in prop_schema["enum"])
            return "string"
        if t == "integer":
            return "number"
        if t == "number":
            return "number"
        if t == "boolean":
            return "boolean"
        if t == "array":
            items = prop_schema.get("items", {})
            return f"{prop_type(items)}[]"
        if t == "object":
            return "Record<string, unknown>"
        return "unknown"

    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    for pname, pschema in props.items():
        if "$ref" in pschema:
            pschema = {**pschema, **resolve_ref(pschema["$ref"])}
        optional = "" if pname in required else "?"
        lines.append(f"  {pname}{optional}: {prop_type(pschema)};")
    lines.append("}")
    return "\n".join(lines)


def _emit_models() -> str:
    """Build the full ``generated.ts`` document."""
    models: list[type[Any]] = [
        EffectBase,
        EffectCreate,
        Effect,
        Section,
        AudioAnalysis,
        Palette,
        PlanSection,
        Motif,
        ShowPlan,
        RankedEffect,
        EffectCandidates,
        EffectsListResponse,
        SemanticSearchRequest,
        SemanticSearchHit,
        ProjectCreate,
        Project,
        ProjectDetail,
        ShowBase,
        ShowCreate,
        Show,
        ShowSummary,
    ]
    chunks: list[str] = [
        "/* eslint-disable */",
        "/* Auto-generated by scripts/gen_types.py — do not edit by hand. */",
        "",
    ]
    emitted_defs: dict[str, Any] = {}
    for model in models:
        schema = model.model_json_schema()
        defs = schema.pop("$defs", {})
        emitted_defs.update(defs)
        name = schema.get("title", model.__name__)
        merged_defs = {**emitted_defs, **defs}
        chunks.append(_schema_to_ts(name, schema, merged_defs))
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def main() -> None:
    """CLI entry: write ``generated.ts`` or ``--check`` against the repo file."""
    parser = argparse.ArgumentParser(description="Generate TypeScript types from Pydantic models.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with code 1 if generated output differs from the committed file.",
    )
    args = parser.parse_args()
    generated = _emit_models()
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    if args.check:
        if not OUT_PATH.is_file():
            sys.stderr.write(f"Missing {OUT_PATH}\n")
            raise SystemExit(1)
        existing = OUT_PATH.read_text(encoding="utf-8")
        if existing != generated:
            sys.stderr.write("generated.ts is out of date; run: python scripts/gen_types.py\n")
            raise SystemExit(1)
        return
    OUT_PATH.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
